packages:
  - packages/*
  - apps/*
  - apps/fixtures/*
  - '!**/.tmp/**'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - msw
  - prisma

minimumReleaseAgeExclude:
  - '@tsdown/css@0.22.12'
  - tsdown@0.22.12
  - verkit@0.1.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - cypress
  - esbuild
