packages:
  # all packages in subdirs of packages/ and examples/
  - "packages/*"
  - "examples/*"
  - "tests/*"
  - "docs"
  - "!**/.tmp/**"
options:
  prefer-workspace-packages: true
  strict-peer-dependencies: false
