packages:
  - packages/*
  - apps/*
  - apps/fixtures/*
  - "!**/.tmp/**"

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - better-sqlite3
  - msw
  - prisma

onlyBuiltDependencies:
  - cypress
  - esbuild
