packages:
  - packages/*
  - apps/*
  - apps/fixtures/*
  - '!**/.tmp/**'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - msw
  - prisma

minimumReleaseAgeExclude:
  - srvx@0.12.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - cypress
  - esbuild
