# CronJob
name: ⏱️ Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    if: github.repository == 'solidjs/solid-start'
    runs-on: ubuntu-latest
    steps:
      - name: needs reproduction
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "needs reproduction"
          inactive-day: 3
