name: Contributing Compliance

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
        with:
          body-fail: false
          body-regex: '[\s\S]*' # Accept any body including newlines
          body-auto-close: false
          ignore-authors: |-
            allcontributors
            allcontributors[bot]
            renovate
            renovate[bot]
          ignore-team-members: true
